"""add columns to table

Revision ID: 493c9e1ef9cc
Revises: 67f5d67aea55
Create Date: 2023-09-18 21:31:59.010447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493c9e1ef9cc'
down_revision = '67f5d67aea55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plants')
    # ### end Alembic commands ###
